// The curated map of what a JOBSEEKER sees on the Tài khoản (account) screens of svn-web,
// in on-screen order. Every row names copy-module paths; the text itself is resolved by
// build-copy.mjs from svn-web, never typed here.
//
// Each row was checked against the component that renders it (svn-web, branch dev).
// Conditional rows carry a `note`; mobile-only / desktop-only text says so in `note`.
//
// Roots (see dump-copy.mjs): dict.* (dictionaries/*.json), header, roleTabs, candidateRequired,
// signUpPanel, signIn, signUp, join, phone, recovery, loginRequired, plus the schema probes
// joinSchema / signInSchema / recoverySchema / resetSchema and content (ad-slot labels).

const DESKTOP = 'Chỉ trên máy tính'
const MOBILE = 'Chỉ trên điện thoại'

const social = (where = 'Khối mạng xã hội') => [
  { key: 'dict.auth.social.continueWithGoogle', where: `${where} — nút tròn Google (chỉ trình đọc màn hình)`, note: 'Nút chỉ có biểu tượng; chữ này là tên đọc cho trình đọc màn hình' },
  { key: 'dict.auth.social.continueWithFacebook', where: `${where} — nút tròn Facebook (chỉ trình đọc màn hình)` },
  { key: 'dict.auth.social.continueWithLinkedin', where: `${where} — nút tròn LinkedIn (chỉ trình đọc màn hình)` },
  { key: 'dict.auth.social.comingSoon', where: 'Thông báo (toast)', note: 'Khi bấm một nhà cung cấp chưa được bật' },
]

// The phone row (PhoneVerifyField) — shared by the e-mail sign-up form and the social
// completion screen. `abroadCollectsNumber` is on for both, so the abroad hint never shows.
const phoneRow = ({ schema }) => [
  { key: 'phone.label', where: 'Ô Số điện thoại — Nhãn ô' },
  { key: 'phone.liveAbroad', where: 'Ô Số điện thoại — Ô tick bên phải nhãn' },
  { key: 'phone.placeholder', where: 'Ô Số điện thoại — Placeholder' },
  { key: 'phone.verify', where: 'Ô Số điện thoại — Nút bên cạnh', note: 'Chỉ bấm được khi số đúng định dạng VN; ẩn khi tick Tôi đang ở nước ngoài' },
  { key: 'phone.resend', where: 'Ô Số điện thoại — Nút bên cạnh', note: 'Thay cho “Xác thực” khi mã đã được gửi' },
  { key: 'phone.codePlaceholder', where: 'Ô nhập mã (hiện sau khi gửi mã) — Placeholder' },
  { key: 'phone.check', where: 'Ô nhập mã — Nút bên cạnh', note: 'Bấm được khi đủ 6 số' },
  { key: 'phone.timeRemaining', where: 'Dưới ô nhập mã — Thông báo (đỏ)', note: 'Kèm đồng hồ đếm ngược m:ss (vd. “2:56”) — thời hạn của mã' },
  { key: 'phone.verifyErrors.expired', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi đồng hồ về 0 mà chưa xác thực (cũng là lỗi trả về khi bấm Kiểm tra mã hết hạn)' },
  { key: 'phone.resendIn', where: 'Dưới ô Số điện thoại — Thông báo (xám)', note: 'Kèm đồng hồ m:ss; khi phải chờ mới được gửi mã mới và không có mã đang chờ nhập' },
  { key: 'phone.verified', where: 'Dưới ô Số điện thoại — Thông báo (xanh, có dấu ✓)', note: 'Sau khi xác thực thành công' },
  { key: 'phone.changeNumber', where: 'Ô Số điện thoại — Nút bên cạnh', note: 'Thay cho “Xác thực” sau khi đã xác thực' },
  { key: 'phone.send.invalidPhone', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: máy chủ báo số không hợp lệ' },
  { key: 'phone.send.cooldown', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: vừa gửi xong, phải chờ' },
  { key: 'phone.send.locked', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: số bị khoá do nhập sai quá nhiều' },
  { key: 'phone.send.rateLimited', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: quá nhiều yêu cầu' },
  { key: 'phone.send.channelUnavailable', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: kênh Zalo/SMS tạm không dùng được' },
  { key: 'phone.send.alreadyRegistered', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã, hoặc khi bấm Đăng ký: số đã có tài khoản' },
  { key: 'phone.send.error', where: 'Dưới ô Số điện thoại — Lỗi', note: 'Khi gửi mã: lỗi khác' },
  { key: 'phone.verifyErrors.wrongCode', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi bấm Kiểm tra: sai mã' },
  { key: 'phone.verifyErrors.superseded', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi bấm Kiểm tra: đã có mã mới hơn' },
  { key: 'phone.verifyErrors.locked', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi bấm Kiểm tra: số bị khoá' },
  { key: 'phone.verifyErrors.rateLimited', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi bấm Kiểm tra: quá nhiều lần' },
  { key: 'phone.verifyErrors.error', where: 'Dưới ô nhập mã — Lỗi', note: 'Khi bấm Kiểm tra: lỗi khác' },
  ...schema,
]

// The consent block (ConsentBox) — shared by both sign-up screens.
const consentBlock = [
  { key: 'join.consent.sectionLabel', where: 'Khối điều khoản — Tiêu đề' },
  { key: 'join.consent.agreeAll', where: 'Khối điều khoản — Ô tick “Đồng ý tất cả”' },
  { key: 'join.consent.agreeAllHint', where: 'Khối điều khoản — Gợi ý dưới “Đồng ý tất cả”' },
  {
    keys: ['join.consent.personalTerms.before', 'join.consent.personalTerms.terms', 'join.consent.personalTerms.between', 'join.consent.personalTerms.privacy', 'join.consent.personalTerms.after'],
    where: 'Khối điều khoản — Ô tick bắt buộc (chữ đậm)',
    note: '“Điều khoản dịch vụ” và “Chính sách bảo mật” là 2 link gạch chân trong câu',
  },
  { key: 'join.consent.locationService', where: 'Khối điều khoản — Ô tick tuỳ chọn 1' },
  { key: 'join.consent.marketingEmail', where: 'Khối điều khoản — Ô tick tuỳ chọn 2' },
  { key: 'join.consent.marketingSms', where: 'Khối điều khoản — Ô tick tuỳ chọn 3' },
]

export const SCREENS = [
  // ───────────────────────────────────────────────────────────── SU
  {
    id: 'SU',
    screen: 'Đăng ký — chọn cách',
    path: '/auth/sign-up',
    note: 'Bước 1 đăng ký. Trái: tab vai trò + cách đăng ký; phải: banner 5 slide tự chạy (3 giây/slide). Không có footer.',
    items: [
      { key: 'signUp.headerWordmark', where: 'Header — chữ cạnh logo', note: DESKTOP },
      { key: 'header.jobseekerHome', where: 'Header — link bên phải', note: DESKTOP },
      { key: 'signUp.srHeading', where: 'Tiêu đề trang (chỉ trình đọc màn hình)' },
      { key: 'roleTabs.candidate', where: 'Tab vai trò — Ứng viên (đang chọn)' },
      { key: 'roleTabs.employer', where: 'Tab vai trò — Nhà tuyển dụng', note: 'Bấm sẽ chuyển thẳng sang form đăng ký nhà tuyển dụng' },
      { key: 'signUp.socialTitle', where: 'Khối mạng xã hội — Tiêu đề (giữa 2 vạch kẻ)' },
      ...social(),
      { key: 'signUpPanel.createWithEmail', where: 'Nút viền xanh' },
      { key: 'join.shell.haveAccount', where: 'Dòng cuối — câu dẫn' },
      { key: 'join.shell.signIn', where: 'Dòng cuối — link (gạch chân)' },
      { key: 'signUp.slidesLabel', where: 'Banner phải — dãy chấm chuyển slide (chỉ trình đọc màn hình)', note: 'Mỗi chấm đọc là “1/5”, “2/5”… (số, không phải chữ)' },
      { keys: ['signUp.slides[0].titleBefore', 'signUp.slides[0].titleAccent', 'signUp.slides[0].titleAfter'], where: 'Banner phải — slide 1, tiêu đề', note: 'Phần “dùng mọi dịch vụ” in màu xanh; xuống dòng sau dấu phẩy' },
      { key: 'signUp.slides[0].body', where: 'Banner phải — slide 1, nội dung' },
      { keys: ['signUp.slides[1].titleBefore', 'signUp.slides[1].titleAccent', 'signUp.slides[1].titleAfter'], where: 'Banner phải — slide 2, tiêu đề', note: 'Phần “Điểm mạnh và năng khiếu” in màu xanh. Nội dung theo Saramin Hàn Quốc — VN chưa có bài kiểm tra năng khiếu' },
      { key: 'signUp.slides[1].body', where: 'Banner phải — slide 2, nội dung', note: 'Dịch vụ chỉ có ở Hàn Quốc' },
      { keys: ['signUp.slides[2].titleBefore', 'signUp.slides[2].titleAccent', 'signUp.slides[2].titleAfter'], where: 'Banner phải — slide 3, tiêu đề', note: 'Phần “được AI gợi ý” in màu xanh' },
      { key: 'signUp.slides[2].body', where: 'Banner phải — slide 3, nội dung' },
      { keys: ['signUp.slides[3].titleBefore', 'signUp.slides[3].titleAccent', 'signUp.slides[3].titleAfter'], where: 'Banner phải — slide 4, tiêu đề', note: 'Phần “nhận đề nghị vị trí” in màu xanh. Dịch vụ chỉ có ở Hàn Quốc (VN chưa có hộp thư đề nghị)' },
      { key: 'signUp.slides[3].body', where: 'Banner phải — slide 4, nội dung', note: 'Dịch vụ chỉ có ở Hàn Quốc' },
      { keys: ['signUp.slides[4].titleBefore', 'signUp.slides[4].titleAccent', 'signUp.slides[4].titleAfter'], where: 'Banner phải — slide 5, tiêu đề', note: 'Phần “nhận thưởng chúc mừng!” in màu xanh. Dịch vụ chỉ có ở Hàn Quốc' },
      { key: 'signUp.slides[4].body', where: 'Banner phải — slide 5, nội dung', note: 'Thưởng 500.000 KRW — chương trình của Hàn Quốc, tiền won' },
    ],
  },

  // ───────────────────────────────────────────────────────────── SD
  {
    id: 'SD',
    screen: 'Đăng ký — form email',
    path: '/auth/sign-up/detail',
    note: 'Bước 2 đăng ký bằng email. Thứ tự ô cố định: Họ tên, Email, Mật khẩu, Số điện thoại, Ngày sinh. Mặc định xác thực bằng số điện thoại (Zalo); tick “Tôi đang ở nước ngoài” thì xác thực bằng email. Không có ô nào gắn dấu *. Không có footer.',
    items: [
      { key: 'signUp.headerWordmark', where: 'Header — chữ cạnh logo', note: DESKTOP },
      { key: 'header.jobseekerHome', where: 'Header — link bên phải', note: DESKTOP },
      { key: 'header.defaultMobileTitle', where: 'Header — tiêu đề giữa', note: `${MOBILE}. Màn đăng ký nhưng tiêu đề đang là “Đăng nhập” (mặc định của header) — cần xem lại` },
      { key: 'signUpPanel.detailHeading', where: 'Tiêu đề trang' },

      { key: 'join.form.fullName', where: 'Ô Họ và tên — Nhãn ô' },
      { key: 'join.form.fullNamePlaceholder', where: 'Ô Họ và tên — Placeholder' },
      { key: 'joinSchema.fullNameRequired', where: 'Ô Họ và tên — Lỗi', note: 'Khi rời ô mà để trống' },
      { key: 'joinSchema.fullNameMin', where: 'Ô Họ và tên — Lỗi', note: 'Khi chỉ nhập 1 ký tự' },
      { key: 'joinSchema.fullNameMax', where: 'Ô Họ và tên — Lỗi', note: 'Khi quá 100 ký tự' },
      { key: 'joinSchema.fullNameFormat', where: 'Ô Họ và tên — Lỗi', note: 'Khi có số, ký hiệu hoặc 2 dấu cách liền nhau' },

      { key: 'join.form.email', where: 'Ô Email — Nhãn ô' },
      { key: 'join.form.emailPlaceholder', where: 'Ô Email — Placeholder' },
      { key: 'join.form.emailHint', where: 'Ô Email — Gợi ý dưới ô', note: 'Luôn hiện, kể cả khi có lỗi (nằm dưới lỗi). Không hiện khi tick Tôi đang ở nước ngoài' },
      { key: 'joinSchema.emailRequired', where: 'Ô Email — Lỗi', note: 'Khi rời ô mà để trống' },
      { key: 'joinSchema.emailInvalid', where: 'Ô Email — Lỗi', note: 'Khi sai định dạng email' },
      { key: 'dict.auth.duplicateAccount', where: 'Ô Email — Lỗi', note: 'Sau khi bấm Đăng ký: email đã có tài khoản' },
      { key: 'dict.auth.deletedAccountEmail', where: 'Ô Email — Lỗi', note: 'Sau khi bấm Đăng ký: email thuộc tài khoản đã xoá' },
      { key: 'join.form.emailVerify.verify', where: 'Ô Email — Nút bên cạnh', note: 'Khi tick Tôi đang ở nước ngoài (email thay số điện thoại để xác thực)' },
      { key: 'join.form.emailVerify.resend', where: 'Ô Email — Nút bên cạnh', note: 'Khi tick Tôi đang ở nước ngoài, sau khi mã đã được gửi' },
      { key: 'join.form.emailVerify.codePlaceholder', where: 'Ô nhập mã email — Placeholder', note: 'Khi tick Tôi đang ở nước ngoài, sau khi gửi mã' },
      { key: 'join.form.emailVerify.check', where: 'Ô nhập mã email — Nút bên cạnh', note: 'Khi tick Tôi đang ở nước ngoài' },
      { key: 'join.form.emailVerify.codeSentTo', where: 'Dưới ô nhập mã email — Thông báo (xám)', note: '{email} là địa chỉ đã che, vd. “s***@e***”' },
      { key: 'join.form.emailVerify.timeRemaining', where: 'Dưới ô nhập mã email — Thông báo (đỏ)', note: 'Kèm đồng hồ m:ss — thời hạn của mã' },
      { key: 'join.form.emailVerify.verifyErrors.expired', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi đồng hồ về 0, hoặc bấm Kiểm tra mã đã hết hạn' },
      { key: 'join.form.emailVerify.verified', where: 'Dưới ô Email — Thông báo (xanh, có dấu ✓)', note: 'Sau khi xác thực email thành công' },
      { key: 'join.form.emailVerify.changeEmail', where: 'Ô Email — Nút bên cạnh', note: 'Thay cho “Xác thực” sau khi đã xác thực' },
      { key: 'join.form.emailVerify.send.invalidEmail', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: email không hợp lệ' },
      { key: 'join.form.emailVerify.send.cooldown', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: vừa gửi xong, phải chờ' },
      { key: 'join.form.emailVerify.send.rateLimited', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: quá nhiều lần (khi hết thời gian chờ hoặc máy chủ không báo thời gian)' },
      { key: 'join.form.emailVerify.send.rateLimitedIn', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: quá nhiều lần, đang đếm ngược; {time} là m:ss' },
      { key: 'join.form.emailVerify.send.alreadyRegistered', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: email đã có tài khoản' },
      { key: 'join.form.emailVerify.send.deletedAccount', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: email thuộc tài khoản đã xoá' },
      { key: 'join.form.emailVerify.send.error', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã: lỗi khác' },
      { key: 'join.form.emailVerify.verifyErrors.wrongCode', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi bấm Kiểm tra: sai mã' },
      { key: 'join.form.emailVerify.verifyErrors.superseded', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi bấm Kiểm tra: đã có mã mới hơn' },
      { key: 'join.form.emailVerify.verifyErrors.alreadyRegistered', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi bấm Kiểm tra: email vừa được đăng ký trong lúc xác thực' },
      { key: 'join.form.emailVerify.verifyErrors.rateLimited', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi bấm Kiểm tra: quá nhiều lần' },
      { key: 'join.form.emailVerify.verifyErrors.error', where: 'Dưới ô nhập mã email — Lỗi', note: 'Khi bấm Kiểm tra: lỗi khác' },
      { key: 'joinSchema.emailUnverified', where: 'Ô Email — Lỗi', note: 'Khi tick Tôi đang ở nước ngoài, nhập email hợp lệ rồi rời ô (hoặc bấm Đăng ký) mà chưa xác thực; ẩn trong lúc đang chờ nhập mã' },

      { key: 'join.form.password', where: 'Ô Mật khẩu — Nhãn ô' },
      { key: 'join.form.passwordPlaceholder', where: 'Ô Mật khẩu — Placeholder' },
      { key: 'join.form.showPassword', where: 'Ô Mật khẩu — nút hình con mắt (chỉ trình đọc màn hình)' },
      { key: 'join.form.hidePassword', where: 'Ô Mật khẩu — nút hình con mắt (chỉ trình đọc màn hình)', note: 'Khi mật khẩu đang hiện' },
      { key: 'join.form.passwordHint', where: 'Ô Mật khẩu — Gợi ý dưới ô', note: 'Khi ô trống. Chuyển thành chữ đỏ (là thông báo lỗi) khi sai quy tắc mật khẩu — sau khi bấm Đăng ký hoặc khi đã gõ' },
      { key: 'join.form.passwordRule.length', where: 'Ô Mật khẩu — danh sách kiểm tra, dòng 1', note: 'Khi bắt đầu gõ; dòng đạt có dấu ✓ xanh' },
      { key: 'join.form.passwordRule.number', where: 'Ô Mật khẩu — danh sách kiểm tra, dòng 2', note: 'Khi bắt đầu gõ' },
      { key: 'join.form.passwordRule.symbol', where: 'Ô Mật khẩu — danh sách kiểm tra, dòng 3', note: 'Khi bắt đầu gõ' },
      { key: 'join.form.passwordRule.uppercase', where: 'Ô Mật khẩu — danh sách kiểm tra, dòng 4', note: 'Khi bắt đầu gõ' },
      { key: 'join.form.passwordValid', where: 'Ô Mật khẩu — Thông báo (xanh)', note: 'Thay cả danh sách kiểm tra khi đạt đủ 4 quy tắc' },
      { key: 'joinSchema.passwordEqualsEmail', where: 'Ô Mật khẩu — Lỗi', note: 'Khi mật khẩu trùng email' },
      { key: 'dict.auth.weakPassword', where: 'Ô Mật khẩu — Lỗi', note: 'Sau khi bấm Đăng ký: máy chủ từ chối mật khẩu' },

      ...phoneRow({
        schema: [
          { key: 'joinSchema.phoneRequired', where: 'Ô Số điện thoại — Lỗi', note: 'Khi rời ô hoặc bấm Đăng ký mà để trống' },
          { key: 'joinSchema.phoneFormat', where: 'Ô Số điện thoại — Lỗi', note: 'Khi số không đúng 9 số (di động) / 10 số (cố định)' },
          { key: 'joinSchema.phoneUnverified', where: 'Ô Số điện thoại — Lỗi', note: 'Chỉ sau khi bấm Đăng ký mà chưa xác thực số; ẩn trong lúc đang chờ nhập mã' },
          { key: 'joinSchema.phoneAbroadFormat', where: 'Ô Số điện thoại — Lỗi', note: 'Khi tick Tôi đang ở nước ngoài: số quá ngắn' },
          { key: 'dict.auth.phoneProofInvalid', where: 'Ô Số điện thoại — Lỗi', note: 'Sau khi bấm Đăng ký: phiên xác thực số đã hết hạn' },
        ],
      }),

      { key: 'join.form.dob', where: 'Ô Ngày sinh — Nhãn ô' },
      { key: 'join.form.dobPlaceholder', where: 'Ô Ngày sinh — Placeholder' },
      { key: 'join.form.dobOpenCalendar', where: 'Ô Ngày sinh — nút lịch (chỉ trình đọc màn hình)' },
      { key: 'join.form.dobClear', where: 'Ô Ngày sinh — nút xoá (chỉ trình đọc màn hình)', note: 'Khi đã có ngày' },
      { key: 'joinSchema.dobRequired', where: 'Ô Ngày sinh — Lỗi', note: 'Khi để trống hoặc ngày không có thật' },
      { key: 'joinSchema.dobFuture', where: 'Ô Ngày sinh — Lỗi', note: 'Khi chọn ngày trong tương lai' },
      { key: 'joinSchema.dobImplausible', where: 'Ô Ngày sinh — Lỗi', note: 'Khi trên 120 tuổi' },
      { key: 'joinSchema.dobMinAge', where: 'Ô Ngày sinh — Lỗi', note: 'Khi dưới 15 tuổi (ngưỡng 15 đang chờ xác nhận pháp lý VN)' },

      ...consentBlock,

      { key: 'join.form.submit', where: 'Nút chính' },
      { key: 'join.form.submitting', where: 'Nút chính', note: 'Trong lúc gửi (kèm biểu tượng xoay)' },
      { key: 'dict.auth.rateLimited', where: 'Thông báo lỗi (toast)', note: 'Sau khi bấm Đăng ký: quá nhiều yêu cầu' },
      { key: 'dict.auth.error', where: 'Thông báo lỗi (toast)', note: 'Sau khi bấm Đăng ký: lỗi khác' },
      { key: 'join.shell.haveAccount', where: 'Dòng cuối — câu dẫn' },
      { key: 'join.shell.signIn', where: 'Dòng cuối — link' },
    ],
  },

  // ───────────────────────────────────────────────────────────── CS
  {
    id: 'CS',
    screen: 'Hoàn tất đăng ký (mạng xã hội)',
    path: '/auth/complete-signup',
    note: 'Sau khi đăng nhập Google/Facebook/LinkedIn lần đầu. Hỏi số điện thoại (xác thực) + điều khoản; email lấy từ nhà cung cấp (khoá, nền xám) — chỉ hỏi email khi nhà cung cấp không trả email.',
    items: [
      { key: 'header.jobseekerHome', where: 'Header — link bên phải', note: DESKTOP },
      { key: 'header.defaultMobileTitle', where: 'Header — tiêu đề giữa', note: `${MOBILE}. Màn đăng ký nhưng tiêu đề đang là “Đăng nhập” — cần xem lại` },
      { key: 'dict.auth.completeSignup.title', where: 'Tiêu đề trang' },
      { key: 'dict.auth.completeSignup.pendingExpired', where: 'Hộp thông báo đỏ (thay cả form)', note: 'Khi phiên đăng nhập mạng xã hội đã hết hạn / lỗi khác khi gửi' },
      { key: 'dict.auth.completeSignup.duplicate', where: 'Hộp thông báo đỏ', note: 'Sau khi bấm Tiếp tục: email đã có tài khoản' },
      { key: 'dict.auth.completeSignup.deletedEmail', where: 'Hộp thông báo đỏ', note: 'Sau khi bấm Tiếp tục: email thuộc tài khoản đã xoá (không có link đăng nhập)' },
      { key: 'dict.auth.completeSignup.alreadyLinkedUnverified', where: 'Hộp thông báo đỏ', note: 'Sau khi bấm Tiếp tục: tài khoản MXH đã đăng ký nhưng chưa xác thực' },
      { key: 'dict.auth.completeSignup.goToSignIn', where: 'Hộp thông báo đỏ — link', note: 'Dưới các thông báo trên, trừ trường hợp email đã xoá' },
      ...phoneRow({
        schema: [
          { key: 'phone.abroadInvalid', where: 'Ô Số điện thoại — Lỗi', note: 'Khi tick Tôi đang ở nước ngoài và số không hợp lệ (khi gõ hoặc máy chủ báo)' },
        ],
      }),
      { key: 'dict.auth.completeSignup.emailLabel', where: 'Ô Email — Nhãn ô' },
      { key: 'dict.auth.completeSignup.emailPlaceholder', where: 'Ô Email — Placeholder', note: 'Chỉ khi nhà cung cấp không trả email (ô nhập được)' },
      { key: 'join.form.emailVerify.verify', where: 'Ô Email — Nút bên cạnh', note: 'Chỉ khi không có email từ nhà cung cấp VÀ tick Tôi đang ở nước ngoài' },
      { key: 'join.form.emailVerify.resend', where: 'Ô Email — Nút bên cạnh', note: 'Như trên, sau khi gửi mã' },
      { key: 'join.form.emailVerify.codePlaceholder', where: 'Ô nhập mã email — Placeholder', note: 'Như trên' },
      { key: 'join.form.emailVerify.check', where: 'Ô nhập mã email — Nút bên cạnh', note: 'Như trên' },
      { key: 'join.form.emailVerify.verified', where: 'Dưới ô Email — Thông báo (xanh)', note: 'Sau khi xác thực email' },
      { key: 'join.form.emailVerify.changeEmail', where: 'Ô Email — Nút bên cạnh', note: 'Sau khi xác thực email' },
      { key: 'join.form.emailVerify.send.invalidEmail', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã' },
      { key: 'join.form.emailVerify.send.cooldown', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã' },
      { key: 'join.form.emailVerify.send.rateLimited', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã (màn này không dùng bản có đồng hồ)' },
      { key: 'join.form.emailVerify.send.alreadyRegistered', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã' },
      { key: 'join.form.emailVerify.send.deletedAccount', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã' },
      { key: 'join.form.emailVerify.send.error', where: 'Dưới ô Email — Lỗi', note: 'Khi gửi mã' },
      { key: 'join.form.emailVerify.verifyErrors.wrongCode', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra' },
      { key: 'join.form.emailVerify.verifyErrors.expired', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra (màn này không có đồng hồ đếm ngược)' },
      { key: 'join.form.emailVerify.verifyErrors.superseded', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra' },
      { key: 'join.form.emailVerify.verifyErrors.alreadyRegistered', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra' },
      { key: 'join.form.emailVerify.verifyErrors.rateLimited', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra' },
      { key: 'join.form.emailVerify.verifyErrors.error', where: 'Dưới ô Email — Lỗi', note: 'Khi bấm Kiểm tra' },
      ...consentBlock,
      { key: 'dict.auth.completeSignup.submit', where: 'Nút chính', note: 'Chỉ bấm được khi đã tick điều khoản bắt buộc và xác thực xong; trong lúc gửi chỉ hiện biểu tượng xoay (không có chữ)' },
    ],
  },

  // ───────────────────────────────────────────────────────────── SI
  {
    id: 'SI',
    screen: 'Đăng nhập',
    path: '/auth/sign-in',
    note: 'Một màn cho cả 2 loại tài khoản (tab). Chỉ liệt kê tab Ứng viên. Màn máy tính: thẻ 2 cột — trái là minh hoạ + nút đăng ký, phải là form. Trang không có tiêu đề hiển thị (cũng không có tiêu đề cho trình đọc màn hình).',
    items: [
      { key: 'header.jobseekerHome', where: 'Header — link bên phải 1', note: DESKTOP },
      { key: 'header.employerHome', where: 'Header — link bên phải 2', note: DESKTOP },
      { key: 'signIn.panelTitle', where: 'Cột trái — Tiêu đề (3 dòng)', note: DESKTOP },
      { key: 'signUpPanel.ctaCandidate', where: 'Cột trái — Nút viền (đi tới Đăng ký)', note: `${DESKTOP} — trên điện thoại màn đăng nhập không có link đăng ký` },
      { key: 'dict.auth.verifiedBanner', where: 'Hộp thông báo xanh (trên form)', note: 'Khi mở từ link xác thực email thành công (?verified=1)' },
      { key: 'dict.auth.verifyFailedBanner', where: 'Hộp thông báo đỏ (trên form)', note: 'Khi link xác thực email sai/hết hạn (?error=verify_failed)' },
      { key: 'dict.auth.wrongRoleBanner', where: 'Hộp thông báo đỏ (trên form)', note: 'Khi bị chuyển về từ khu vực dành cho loại tài khoản khác (?reason=wrong-role)' },
      { key: 'dict.auth.oauth.state', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH bị gián đoạn (?error=oauth_state)' },
      { key: 'dict.auth.oauth.inactive', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH: tài khoản không hoạt động (?error=oauth_inactive)' },
      { key: 'dict.auth.oauth.unverified', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH: email chưa xác thực (?error=oauth_unverified)' },
      { key: 'dict.auth.oauth.email', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH: email từ nhà cung cấp chưa xác thực (?error=oauth_email)' },
      { key: 'dict.auth.oauth.failed', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH thất bại (?error=oauth_failed / oauth_code)' },
      { key: 'dict.auth.oauth.deleted', where: 'Hộp thông báo đỏ (trên form)', note: 'Đăng nhập MXH: tài khoản đã xoá (?error=oauth_deleted)' },
      { key: 'dict.auth.checkEmailTitle', where: 'Hộp “Kiểm tra email” — Tiêu đề', note: 'Khi đăng nhập bằng email chưa xác thực (hiện trên form, kèm địa chỉ email)' },
      { key: 'dict.auth.checkEmailBody', where: 'Hộp “Kiểm tra email” — Nội dung', note: 'Như trên' },
      { key: 'dict.auth.resend', where: 'Hộp “Kiểm tra email” — Nút viền', note: 'Như trên' },
      { key: 'dict.auth.resendSent', where: 'Hộp “Kiểm tra email” — Thông báo (xanh)', note: 'Sau khi bấm gửi lại thành công' },
      { key: 'dict.auth.rateLimited', where: 'Hộp “Kiểm tra email” — Lỗi', note: 'Khi gửi lại: quá nhiều yêu cầu' },
      { key: 'dict.auth.error', where: 'Hộp “Kiểm tra email” — Lỗi', note: 'Khi gửi lại: lỗi khác' },
      { key: 'roleTabs.candidate', where: 'Tab vai trò — Ứng viên' },
      { key: 'roleTabs.employer', where: 'Tab vai trò — Nhà tuyển dụng', note: 'Chuyển sang form đăng nhập nhà tuyển dụng (ngoài phạm vi)' },
      { key: 'signIn.labels.email', where: 'Ô Email — Nhãn nổi (nằm trong ô, thu nhỏ lên trên khi gõ)' },
      { key: 'signInSchema.emailInvalid', where: 'Ô Email — Lỗi', note: 'Khi bấm Đăng nhập với email trống hoặc sai định dạng' },
      { key: 'dict.auth.emailNotVerified', where: 'Ô Email — Lỗi', note: 'Khi email chưa xác thực (cùng lúc với hộp “Kiểm tra email”)' },
      { key: 'signIn.labels.password', where: 'Ô Mật khẩu — Nhãn nổi' },
      { key: 'signIn.showPassword', where: 'Ô Mật khẩu — nút con mắt (chỉ trình đọc màn hình)' },
      { key: 'signIn.hidePassword', where: 'Ô Mật khẩu — nút con mắt (chỉ trình đọc màn hình)', note: 'Khi mật khẩu đang hiện' },
      { key: 'signInSchema.passwordRequired', where: 'Ô Mật khẩu — Lỗi', note: 'Khi để trống' },
      { key: 'signInSchema.passwordMax', where: 'Ô Mật khẩu — Lỗi', note: 'Khi quá 72 ký tự' },
      { key: 'dict.auth.invalidCredentials', where: 'Ô Mật khẩu — Lỗi', note: 'Khi sai email hoặc mật khẩu' },
      { key: 'dict.auth.inactiveAccount', where: 'Ô Mật khẩu — Lỗi', note: 'Khi tài khoản bị vô hiệu hoá' },
      { key: 'dict.auth.deletedAccount', where: 'Ô Mật khẩu — Lỗi', note: 'Khi tài khoản đã xoá' },
      { key: 'dict.auth.rateLimited', where: 'Ô Mật khẩu — Lỗi', note: 'Khi đăng nhập quá nhiều lần' },
      { key: 'dict.auth.error', where: 'Ô Mật khẩu — Lỗi', note: 'Lỗi khác' },
      { key: 'signIn.keepLoggedIn', where: 'Ô tick dưới ô Mật khẩu' },
      { key: 'signIn.submit', where: 'Nút chính' },
      { key: 'signIn.submitting', where: 'Nút chính', note: 'Trong lúc gửi' },
      { key: 'signIn.forgotPassword', where: 'Link dưới nút' },
      { key: 'signIn.socialDivider', where: 'Vạch chia — chữ giữa' },
      ...social('Hàng mạng xã hội'),
    ],
  },

  // ───────────────────────────────────────────────────────────── LR
  {
    id: 'LR',
    screen: 'Hộp “Cần đăng nhập”',
    path: '(hộp thoại — mọi trang)',
    note: 'Hiện ngay trên trang khi khách chưa đăng nhập bấm thao tác cần tài khoản ứng viên (ứng tuyển, lưu tin, theo dõi…). Đăng nhập xong thì ở lại trang. Phần cuối: hộp nhỏ ở góc dành cho người đang đăng nhập bằng tài khoản nhà tuyển dụng.',
    items: [
      { key: 'loginRequired.title', where: 'Hộp — Tiêu đề', note: 'Chữ “đăng nhập” trong câu tô màu xanh' },
      { key: 'loginRequired.highlight', where: 'Hộp — phần tô xanh trong tiêu đề', note: 'Không hiện riêng; phải trùng đúng một đoạn của tiêu đề, nếu không sẽ không tô màu' },
      { key: 'dict.common.a11y.close', where: 'Hộp — nút X góc phải (chỉ trình đọc màn hình)' },
      { key: 'signIn.labels.email', where: 'Ô Email — Nhãn nổi' },
      { key: 'signInSchema.emailInvalid', where: 'Ô Email — Lỗi', note: 'Khi trống hoặc sai định dạng' },
      { key: 'dict.auth.emailNotVerified', where: 'Ô Email — Lỗi', note: 'Khi email chưa xác thực (hộp này không có khối “Kiểm tra email”)' },
      { key: 'signIn.labels.password', where: 'Ô Mật khẩu — Nhãn nổi' },
      { key: 'signIn.showPassword', where: 'Ô Mật khẩu — nút con mắt (chỉ trình đọc màn hình)' },
      { key: 'signIn.hidePassword', where: 'Ô Mật khẩu — nút con mắt (chỉ trình đọc màn hình)', note: 'Khi mật khẩu đang hiện' },
      { key: 'signInSchema.passwordRequired', where: 'Ô Mật khẩu — Lỗi', note: 'Khi để trống' },
      { key: 'signInSchema.passwordMax', where: 'Ô Mật khẩu — Lỗi', note: 'Khi quá 72 ký tự' },
      { key: 'dict.auth.invalidCredentials', where: 'Ô Mật khẩu — Lỗi', note: 'Khi sai email hoặc mật khẩu' },
      { key: 'dict.auth.deletedAccount', where: 'Ô Mật khẩu — Lỗi', note: 'Khi tài khoản đã xoá' },
      { key: 'dict.auth.rateLimited', where: 'Ô Mật khẩu — Lỗi', note: 'Khi quá nhiều lần' },
      { key: 'dict.auth.error', where: 'Ô Mật khẩu — Lỗi', note: 'Lỗi khác' },
      { key: 'dict.auth.inactiveAccount', where: 'Thông báo lỗi (toast)', note: 'Khi tài khoản bị vô hiệu hoá (ở màn Đăng nhập thì hiện dưới ô Mật khẩu)' },
      { key: 'signIn.keepLoggedIn', where: 'Ô tick 1 (cùng hàng)' },
      { key: 'loginRequired.rememberId', where: 'Ô tick 2 (cùng hàng)' },
      { key: 'signIn.submit', where: 'Nút chính' },
      { key: 'signIn.submitting', where: 'Nút chính', note: 'Trong lúc gửi' },
      { key: 'signIn.forgotPassword', where: 'Hàng link dưới nút — link 1' },
      { key: 'signIn.signUp', where: 'Hàng link dưới nút — link 2' },
      { key: 'signIn.socialDivider', where: 'Vạch chia — chữ giữa' },
      ...social('Hàng mạng xã hội'),
      { key: 'dict.errors.forbidden', where: 'Thông báo lỗi (toast) — thay cho hộp', note: 'Khi đã đăng nhập bằng tài khoản ứng viên nhưng máy chủ vẫn từ chối thao tác' },
      { key: 'candidateRequired.close', where: 'Hộp góc (NTD) — nút X (chỉ trình đọc màn hình)', note: 'Khi đang đăng nhập bằng tài khoản nhà tuyển dụng và bấm thao tác dành cho ứng viên' },
      { key: 'candidateRequired.title', where: 'Hộp góc (NTD) — Tiêu đề', note: 'Như trên' },
      { key: 'candidateRequired.employerBody', where: 'Hộp góc (NTD) — Nội dung', note: 'Như trên' },
      { key: 'candidateRequired.employerWarning', where: 'Hộp góc (NTD) — Cảnh báo (khung xám)', note: 'Như trên' },
      { key: 'candidateRequired.title', where: 'Hộp góc (NTD) — Nút chính', note: 'Dùng lại đúng câu tiêu đề; bấm sẽ tới màn Đăng nhập' },
    ],
  },

  // ───────────────────────────────────────────────────────────── FP
  {
    id: 'FP',
    screen: 'Quên mật khẩu',
    path: '/auth/forgot-password',
    note: '3 bước trên cùng một trang: xác thực bằng số điện thoại hoặc email (mã 6 số) → đặt mật khẩu mới → xong. Màn máy tính rộng (≥1280px) có thêm cột quảng cáo bên phải; dưới khung có thể có banner quảng cáo.',
    items: [
      { key: 'header.jobseekerHome', where: 'Header — link bên phải 1', note: DESKTOP },
      { key: 'header.employerHome', where: 'Header — link bên phải 2', note: DESKTOP },
      { key: 'recovery.reset.title', where: 'Tiêu đề trang', note: 'Cả 3 bước' },
      { key: 'recovery.reset.tabs.phone', where: 'Tab 1' },
      { key: 'recovery.reset.tabs.email', where: 'Tab 2' },
      { key: 'recovery.reset.lead', where: 'Câu hướng dẫn (đậm) trên bảng' },
      { key: 'recovery.reset.phoneLabel', where: 'Bảng — nhãn hàng 1', note: 'Tab số điện thoại' },
      { key: 'recovery.reset.phonePlaceholder', where: 'Bảng — hàng 1, Placeholder', note: 'Tab số điện thoại' },
      { key: 'recovery.reset.emailLabel', where: 'Bảng — nhãn hàng 1', note: 'Tab email' },
      { key: 'recovery.reset.emailPlaceholder', where: 'Bảng — hàng 1, Placeholder', note: 'Tab email' },
      { key: 'recovery.reset.verify', where: 'Bảng — hàng 1, Nút', note: 'Trước khi gửi mã' },
      { key: 'recovery.reset.resendIn', where: 'Bảng — hàng 1, Nút (đang khoá)', note: 'Sau khi gửi, trong thời gian chờ; {seconds} là số giây' },
      { key: 'recovery.reset.resend', where: 'Bảng — hàng 1, Nút', note: 'Hết thời gian chờ' },
      { key: 'recovery.code.label', where: 'Bảng — nhãn hàng 2' },
      { key: 'recovery.code.placeholder', where: 'Bảng — hàng 2, Placeholder', note: 'Sau khi gửi mã' },
      { key: 'recovery.reset.check', where: 'Bảng — hàng 2, Nút', note: 'Sau khi gửi mã' },
      { key: 'recovery.code.expiresIn', where: 'Bảng — dưới ô mã, Thông báo (đỏ)', note: 'Đếm ngược; {seconds} là “2:56” hoặc chỉ số giây khi dưới 1 phút (vd. “45”, không có đơn vị)' },
      { key: 'recovery.code.expired', where: 'Bảng — dưới ô mã, Thông báo (đỏ)', note: 'Khi mã hết hạn' },
      { key: 'recovery.reset.phoneVerified', where: 'Bảng — dưới ô mã, Thông báo (xanh)', note: 'Tab số điện thoại, sau khi xác thực' },
      { key: 'recovery.reset.emailVerified', where: 'Bảng — dưới ô mã, Thông báo (xanh)', note: 'Tab email, sau khi xác thực' },
      { key: 'recoverySchema.phoneFormat', where: 'Dưới bảng — Lỗi', note: 'Khi bấm Xác thực với số không hợp lệ' },
      { key: 'recoverySchema.emailFormat', where: 'Dưới bảng — Lỗi', note: 'Khi bấm Xác thực với email sai định dạng' },
      { key: 'recovery.errors.noAccountPhone', where: 'Dưới bảng — Lỗi', note: 'Khi gửi mã: không có tài khoản dùng số này' },
      { key: 'recovery.errors.noAccountEmail', where: 'Dưới bảng — Lỗi', note: 'Khi gửi mã: không có tài khoản dùng email này' },
      { key: 'recovery.reset.phoneAmbiguous', where: 'Dưới bảng — Lỗi', note: 'Số gắn với nhiều tài khoản (khi gửi mã, hoặc bị đưa về từ bước 2)' },
      { key: 'recovery.errors.rateLimited', where: 'Dưới bảng — Lỗi', note: 'Khi gửi mã quá nhiều; {seconds} là số giây' },
      { key: 'recovery.errors.locked', where: 'Dưới bảng — Lỗi', note: 'Tab số điện thoại: bị khoá do nhập sai nhiều; {seconds} là “m:ss” hoặc số giây (thời gian dài hiện dạng “1440:00”)' },
      { key: 'recovery.errors.lockedNoWait', where: 'Dưới bảng — Lỗi', note: 'Như trên, khi không có thời gian chờ' },
      { key: 'recovery.errors.channelUnavailable', where: 'Dưới bảng — Lỗi', note: 'Tab số điện thoại: kênh gửi mã tạm không dùng được' },
      { key: 'recovery.code.resent', where: 'Dưới bảng — Thông báo (xám)', note: 'Sau khi bấm Gửi lại thành công' },
      { key: 'recovery.errors.wrongCode', where: 'Dưới bảng — Lỗi', note: 'Khi bấm Kiểm tra mà mã chưa đủ 6 số' },
      { key: 'recovery.code.attemptsLeft', where: 'Dưới bảng — Lỗi', note: 'Khi sai mã; {count} là số lần còn lại' },
      { key: 'recovery.code.noAttemptsLeft', where: 'Dưới bảng — Lỗi', note: 'Khi sai mã và hết lượt' },
      { key: 'recovery.errors.expiredCode', where: 'Dưới bảng — Lỗi', note: 'Khi bấm Kiểm tra mã đã hết hạn' },
      { key: 'recovery.errors.supersededCode', where: 'Dưới bảng — Lỗi', note: 'Khi bấm Kiểm tra mã cũ (đã có mã mới hơn)' },
      { key: 'recovery.errors.generic', where: 'Dưới bảng — Lỗi', note: 'Lỗi khác' },
      { key: 'recovery.reset.noAccount', where: 'Dưới bảng — Lỗi', note: 'Bị đưa về từ bước 2: không có tài khoản dùng số này' },
      { key: 'recovery.errors.proofInvalid', where: 'Dưới bảng — Lỗi', note: 'Bị đưa về từ bước 2: phiên xác minh hết hạn' },
      { key: 'recovery.reset.submit', where: 'Nút xanh lớn dưới bảng', note: 'Chỉ bấm được sau khi xác thực' },

      { key: 'recovery.reset.passwordTitle', where: 'Bước 2 — Tiêu đề (đậm)' },
      { key: 'recovery.reset.passwordLead', where: 'Bước 2 — Câu hướng dẫn' },
      { key: 'recovery.reset.newPasswordLabel', where: 'Bước 2 — Ô Mật khẩu mới, Nhãn ô', note: 'Có dấu * đỏ' },
      { key: 'recovery.reset.newPasswordPlaceholder', where: 'Bước 2 — Ô Mật khẩu mới, Placeholder' },
      { key: 'recoverySchema.passwordLength', where: 'Bước 2 — Ô Mật khẩu mới, Lỗi', note: 'Khi bấm Đặt lại: dưới 8 hoặc trên 128 ký tự (cả khi để trống)' },
      { key: 'recoverySchema.passwordDigit', where: 'Bước 2 — Ô Mật khẩu mới, Lỗi', note: 'Thiếu chữ số' },
      { key: 'recoverySchema.passwordSymbol', where: 'Bước 2 — Ô Mật khẩu mới, Lỗi', note: 'Thiếu ký tự đặc biệt' },
      { key: 'recoverySchema.passwordUppercase', where: 'Bước 2 — Ô Mật khẩu mới, Lỗi', note: 'Thiếu chữ in hoa' },
      { key: 'recovery.reset.invalidPassword', where: 'Bước 2 — Ô Mật khẩu mới, Lỗi', note: 'Máy chủ từ chối mật khẩu' },
      { key: 'recovery.reset.confirmLabel', where: 'Bước 2 — Ô Xác nhận, Nhãn ô', note: 'Có dấu * đỏ' },
      { key: 'recovery.reset.confirmPlaceholder', where: 'Bước 2 — Ô Xác nhận, Placeholder' },
      { key: 'recovery.reset.mismatch', where: 'Bước 2 — Ô Xác nhận, Lỗi', note: 'Khi 2 mật khẩu khác nhau' },
      { key: 'recovery.errors.generic', where: 'Bước 2 — Hộp thông báo đỏ', note: 'Lỗi khác khi đặt lại' },
      { key: 'recovery.reset.submit', where: 'Bước 2 — Nút chính' },
      { key: 'recovery.reset.submitting', where: 'Bước 2 — Nút chính', note: 'Trong lúc gửi' },

      { key: 'recovery.reset.doneTitle', where: 'Bước 3 — Tiêu đề (đậm)' },
      { key: 'recovery.reset.doneBody', where: 'Bước 3 — Nội dung' },
      { key: 'recovery.reset.signIn', where: 'Bước 3 — Link' },

      { key: 'recovery.reset.footer.signIn', where: 'Hàng nút dưới khung — nút 1 (có biểu tượng người)', note: 'Cả 3 bước' },
      { key: 'recovery.reset.footer.signUp', where: 'Hàng nút dưới khung — nút 2' },
      { key: 'recovery.reset.footer.help', where: 'Hàng nút dưới khung — nút 3' },
      { key: 'content.bannerLinkLabel', where: 'Banner quảng cáo dưới khung (chỉ trình đọc màn hình)', note: 'Khi có banner và banner có link' },

      { key: 'recovery.wing.recentTitle', where: 'Cột phải — khối “tin đã xem”, Tiêu đề', note: 'Chỉ trên màn hình rộng (≥1280px); kèm số tin' },
      { key: 'recovery.wing.recentEmpty', where: 'Cột phải — khối “tin đã xem”, khi trống', note: 'Như trên' },
      { key: 'recovery.wing.untilFilled', where: 'Cột phải — hạn nộp của tin', note: 'Khi tin không có hạn (có hạn thì hiện “~dd/mm”)' },
      { key: 'dict.common.saveJob', where: 'Cột phải — nút ngôi sao lưu tin (chỉ trình đọc màn hình)', note: '{company} {title} thay bằng tên công ty và tin' },
      { key: 'recovery.wing.more', where: 'Cột phải — nút mở rộng danh sách', note: 'Khi có nhiều hơn số tin hiển thị sẵn' },
      { key: 'recovery.wing.less', where: 'Cột phải — nút thu gọn', note: 'Khi đã mở rộng' },
      { key: 'recovery.wing.recommendBadge', where: 'Cột phải — khối tin đề xuất, nhãn', note: 'Khi có tin đề xuất' },
      { key: 'recovery.wing.apply', where: 'Cột phải — khối tin đề xuất, nút', note: 'Như trên' },
      { key: 'content.bannerLinkLabel', where: 'Cột phải — banner dọc (chỉ trình đọc màn hình)', note: 'Khi có banner và banner có link' },
      { key: 'recovery.wing.top', where: 'Cột phải — nút tròn lên đầu trang' },
      { key: 'recovery.wing.topLabel', where: 'Cột phải — nút lên đầu trang, Tooltip' },
    ],
  },

  // ───────────────────────────────────────────────────────────── RP
  {
    id: 'RP',
    screen: 'Đặt mật khẩu mới (link cũ)',
    path: '/auth/reset-password',
    note: 'Trang mở từ link đặt lại mật khẩu trong email (luồng cũ). Màn máy tính là thẻ 2 cột, cột phải là khối giới thiệu Saramin.',
    items: [
      { key: 'header.jobseekerHome', where: 'Header — link bên phải 1', note: DESKTOP },
      { key: 'header.employerHome', where: 'Header — link bên phải 2', note: DESKTOP },
      { key: 'dict.auth.reset.title', where: 'Header — tiêu đề giữa', note: MOBILE },
      { key: 'dict.auth.reset.title', where: 'Tiêu đề trang', note: 'Ẩn trên điện thoại (đã có ở header)' },
      { key: 'dict.auth.reset.linkExpired', where: 'Hộp thông báo đỏ (thay cả form)', note: 'Khi link không có mã, hết hạn hoặc đã dùng' },
      { key: 'dict.auth.reset.requestNew', where: 'Link dưới hộp thông báo', note: 'Như trên — tới Quên mật khẩu' },
      { key: 'dict.auth.reset.subtitle', where: 'Câu hướng dẫn dưới tiêu đề' },
      { key: 'dict.auth.reset.passwordPlaceholder', where: 'Ô Mật khẩu mới — Placeholder', note: 'Ô không có nhãn' },
      { key: 'resetSchema.passwordMin', where: 'Ô Mật khẩu mới — Lỗi', note: 'Dưới 8 ký tự (cả khi để trống)' },
      { key: 'resetSchema.passwordMax', where: 'Ô Mật khẩu mới — Lỗi', note: 'Trên 128 ký tự' },
      { key: 'resetSchema.passwordNoSpace', where: 'Ô Mật khẩu mới — Lỗi', note: 'Có dấu cách ở đầu/cuối' },
      { key: 'resetSchema.passwordLetterDigit', where: 'Ô Mật khẩu mới — Lỗi', note: 'Thiếu chữ hoặc số' },
      { key: 'resetSchema.passwordSymbol', where: 'Ô Mật khẩu mới — Lỗi', note: 'Thiếu ký tự đặc biệt' },
      { key: 'dict.auth.error', where: 'Ô Mật khẩu mới — Lỗi', note: 'Máy chủ báo lỗi khác' },
      { key: 'dict.auth.reset.submit', where: 'Nút chính', note: 'Không đổi chữ trong lúc gửi' },
      { key: 'dict.auth.panel.title', where: 'Cột phải — Tiêu đề, phần 1', note: DESKTOP },
      { key: 'dict.auth.panel.titleAccent', where: 'Cột phải — Tiêu đề, phần 2 (màu xanh)', note: DESKTOP },
      { key: 'dict.auth.panel.subtitle', where: 'Cột phải — Nội dung', note: DESKTOP },
      { key: 'dict.auth.panel.features[0]', where: 'Cột phải — Danh sách ✓, dòng 1', note: DESKTOP },
      { key: 'dict.auth.panel.features[1]', where: 'Cột phải — Danh sách ✓, dòng 2', note: DESKTOP },
      { key: 'dict.auth.panel.features[2]', where: 'Cột phải — Danh sách ✓, dòng 3', note: DESKTOP },
    ],
  },

  // ───────────────────────────────────────────────────────────── AD
  {
    id: 'AD',
    screen: 'Tài khoản đã xoá',
    path: '/auth/account-deleted',
    note: 'Trang cuối sau khi ứng viên tự xoá tài khoản.',
    items: [
      { key: 'header.jobseekerHome', where: 'Header — link bên phải 1', note: DESKTOP },
      { key: 'header.employerHome', where: 'Header — link bên phải 2', note: DESKTOP },
      { key: 'dict.auth.accountDeleted.title', where: 'Header — tiêu đề giữa', note: MOBILE },
      { key: 'dict.auth.accountDeleted.title', where: 'Tiêu đề trang' },
      { key: 'dict.auth.accountDeleted.body', where: 'Đoạn 1' },
      { key: 'dict.auth.accountDeleted.emailSpent', where: 'Đoạn 2' },
      { key: 'dict.auth.accountDeleted.support', where: 'Đoạn 3' },
      { key: 'dict.auth.accountDeleted.backHome', where: 'Link' },
    ],
  },

  // ───────────────────────────────────────────────────────────── SO
  {
    id: 'SO',
    screen: 'Đăng xuất',
    path: '(menu tài khoản)',
    note: 'Không có trang riêng: bấm là đăng xuất rồi về trang chủ, không có thông báo.',
    items: [
      { key: 'dict.common.logout', where: 'Mục cuối — menu tài khoản ở header (máy tính), menu điện thoại, menu trang hồ sơ, thanh bên / tab Cài đặt tài khoản' },
      { key: 'dict.common.loggingOut', where: 'Cùng vị trí', note: 'Trong lúc đăng xuất (kèm biểu tượng xoay)' },
    ],
  },
]

// Strings in the loaded copy modules that no jobseeker screen renders, by path prefix.
// Each was checked against svn-web (dev): grep finds no read of the property in any UI file,
// or only an employer / corporate screen reads it.
export const IGNORED_PREFIXES = [
  // Slide artwork paths and anchors — not text.
  'signUp.slides[0].image', 'signUp.slides[1].image', 'signUp.slides[2].image', 'signUp.slides[3].image', 'signUp.slides[4].image',
  // Employer registration / employer sign-in only.
  'signUp.employerHeaderWordmark', 'signUpPanel.detailHeadingEmployer', 'signUpPanel.ctaEmployer', 'signIn.placeholders.corporateLoginKey',
  'dict.auth.companyArchived', 'dict.auth.deletedCorporateAccount', 'dict.auth.corporateForgot.', 'dict.auth.corporateSetPassword.',
  // Unreachable: the candidate path never calls the corporate branch that returns it.
  'dict.auth.corporateUnsupported',
  // Defined, never rendered.
  'header.back', // the mobile back button has no accessible name at all
  'candidateRequired.body',
  'signUpPanel.title', 'signUpPanel.titleAccent', 'signUpPanel.subtitle', 'signUpPanel.heading', 'signUpPanel.haveAccount',
  'signIn.heading', 'signIn.tabs.', 'signIn.placeholders.email', 'signIn.placeholders.password', 'signIn.findId', 'signIn.or',
  'signIn.noAccount', 'signIn.employerCta', 'signIn.jobseekerCta',
  'signIn.modal.', // only the unused "corner" placement of the login-required card reads it
  'join.shell.heading', 'join.shell.subtitle', 'join.form.socialDivider', 'join.form.phone', // phone / phonePlaceholder / phoneCountry: the row reads phone.*
  'phone.liveAbroadHint', // only drawn when abroadCollectsNumber is off; both callers turn it on
  'dict.auth.completeSignup.subtitle', 'dict.auth.promo.',
  'dict.auth.forgot.', // the old e-mail-link forgot-password flow; /auth/forgot-password is now the OTP flow
  // Recovery: the find-ID hub, find-ID and results screens were never routed.
  'recovery.wordmark', 'recovery.hub.', 'recovery.findId.', 'recovery.identify.', 'recovery.results.',
  'recovery.code.lead', 'recovery.code.resend', 'recovery.code.changeIdentity', 'recovery.code.submit',
  'recovery.reset.emailLead', 'recovery.errors.companyNotFound',
  // Never shown: the send button is disabled while the box is empty.
  'recoverySchema.phoneRequired', 'recoverySchema.emailRequired',
  // Sign-up password rules: the form withholds these and turns the hint red instead.
  'joinSchema.passwordMin', 'joinSchema.passwordMax', 'joinSchema.passwordDigit', 'joinSchema.passwordSymbol', 'joinSchema.passwordUppercase',
  // Produced by the schema but rendered nowhere: no element reads errors.terms (submit just does nothing).
  'joinSchema.termsRequired',
  // Account-settings modals — outside the auth screens covered here.
  'dict.auth.deleteAccount.', 'dict.auth.changePassword.',
]
